### ISSUE TITLE
LateAppendInto as convenient shorthand for io.Closer and similar use cases

### ISSUE THREAD

**Issue by baez90** [uber-go/multierr#46]
In cases like

```go
func writeToTempFile(content string) (err error) {
	var tmpFile io.WriteCloser
	if tmpFile, err = os.CreateTemp(os.TempDir(), "tmp-*"); err != nil {
		return
	}
	defer func() {
		err = multierr.Append(err, tmpFile.Close())
	}()
	_, err = tmpFile.Write([]byte(content))
	return
}
```

the `AppendInto` seems to be handy but unfortunately it is not because

```go
defer multierr.AppendInto(&err, tmpFile.Close())
```

immediately closes the file.

I would like to propose a `LateAppendInto`:

```go
func LateAppendInto(into *error, errFunc func() error) (errored bool) {
	return multierr.AppendInto(into, errFunc())
}
```

that captures the function returning an `error` to actually call it when the `defer` calls the actual function to improve the initial example to:

```go
func writeToTempFile(content string) (err error) {
	var tmpFile io.WriteCloser
	if tmpFile, err = os.CreateTemp(os.TempDir(), "tmp-*"); err != nil {
		return
	}
	defer multierr.LateAppendInto(&err, tmpFile.Close)
	_, err = tmpFile.Write([]byte(content))
	return
}
```

I'd be glad to create a PR but I thought I'd ask you first what you think and if you would accept something like this.

**Comment by abhinav** [comment]
Hello! The issue with deferred AppendInto is valid, and I suspect it will also trip up newcomers to the language because they wouldn't realize that `defer` will stop at evaluating the outermost call expression.

We would be in favor of solving this, and the approach you've suggested is reasonable, but we would like to pick a name that was clearer---something that made the behavior clear even in non-defer contexts.

I can't think of any good and obvious alternatives. @prashantv do you have any ideas? Some names that might work generically that I'm not sold on are: `AppendCall`, `CallAppend`, `Call`, and `CallInto`, `AppendCallInto`. The general interpretation of these being that they will call the provided function and append the resulting error (if any) into the provided error pointer.

    defer multierr.AppendCallInto(&err, f.Close)

`AppendCallInto` theoretically leave room for `func AppendCall(error, func() error) error` if we ever want to add that.

Besides the name, one other thing I'm unsure about (but don't consider a complete blocker) is a the fixed function signature `func() error`. This wouldn't be able to deal with anything that has multiple arguments without closures which, again, I don't consider a blocker.

    defer multierr.LateAppendInto(&err, func() error { return srv.Shutdown(ctx) })
    // versus
    defer func() { multierr.AppendInto(&err, srv.Shutdown(ctx)) }()

(In general, avoiding reflection in this library is preferable so there aren't many options for this limitation for now.)

**Comment by baez90** [comment]
Hi,

first I'd like to add what I completely missed yesterday because I was bit in a rush: I really appreciate your work with multierr, thank you very much!

Regarding your naming concerns: I'm open for any idea, the `LateAppendInto` was more meant as a working title but I know what you mean. Especially because you're also right that I was completely focused on the `defer` use case but haven't thought of anything besides this very specific usage scenario.

What I can think of would be:

```go
defer multierr.AppendResultInto(&err, f.Close)

// or respectively

err = multierr.AppendResult(err, f.Close)
```

or

```go
defer multierr.AppendIntoFrom(&err, f.Close)

// or respectively

err = multierr.AppendFrom(err, f.Close)
```

or

```go
defer multierr.AppendCleanupInto(&err, f.Close)

// or respectively

err = multierr.AppendCleanup(err, f.Close)
```

or probably like this:

```go
type Errorer func() error // to borrow the idea of 'Closer'

defer multierr.AppendFromErrorerInto(&err, f.Close)

// or respectively

err = multierr.AppendFromErrorer(err, f.Close)
```

but the longer I'm looking at the latest version I really don't like it and no matter if `AppendFromErrorer` or `AppendErrorer` it's rather long and also does not really transport the idea.

If we can't come up with anything better I would also be fine with your suggestion `AppendCall`/`AppendCallInto`?

I spent already a bit of time to think about the signature but I also think that "fixing" this with reflection is not a desirable and even if the usage of generics would already be possible I'm not sure how the ideal signature would look like especially with return parameters, multiple parameters and how to deal with different function names for each combination of input and output and so on and so forth :sweat_smile: and I think it's not a big deal e.g. to come up with functions like:

```go
func ShutdownWithContext(ctx context.Context) func() error {
    return func() error {
        return srv.Shutdown(ctx)
    }
}

// ...

defer multierr.AppendCallInto(&err, ShutdownWithContext(ctx))
```

(I know naming also not that good :smile: )

Probably good enough? Any thoughts?

**Comment by prashantv** [comment]
In terms of names, I think `AppendCallInfo` is the most explicitly, but it's also quite verbose, so I'm wondering whether we should call it `AppendCall` (and if so, it would mean we can't have `func AppendCall(error, func() error) error` in the future).

I think that `func AppendCall(error, func() error) error` is not very useful, since it's the same as `Append(err, f())`, which is less verbose, and probably clearer that the function is called immediately.

Re: closure, we could instead go with an interface, and provide a func --> interface wrapper, but it gets more verbose, e.g.,
```go
type Call interface {
  Err() error
}

func AppendCall(err *error, call Call)

# wapper
type CallFunc func() error

func (cf CallFunc) Err() error { return cf() }

# usage becomes more verbose
defer multierr.AppendCall(&err, multierr.CallFunc(f.Close))
```

That said, we can always start with the closure approach and add a separate method for the interface if there's a common interface that types implement that may contain an error. (The current interface is based on [`bufio.Scanner`'s `Err` method](https://golang.org/pkg/bufio/#Scanner.Err))

**Comment by baez90** [comment]
I like the approach with the `Call` interface.
Naming the method within the interface again might be kinda hard but the `Err` approach is at least straight forward.

I would probably add a second wrapper for `io.Closer` because I expect it to be one of the most common use cases for `AppendCall`.

I think I'll open a PR in the upcoming days and implement the `Call` interface approach to actually 'see' how it feels like and to allow discussions directly on the code?
If another approach will be chosen it's not a lot of effort to rework it anyway.

**Comment by abhinav** [comment]
Hey, sorry about the delay in responding. I like the interface, especially because it fits with `bufio.Scanner`'s `Err` method, but I'd like to suggest we consider other names for the interface.

It's not clear whether `Call.Err` will run the operation or return the previously recorded result of running the operation, and what the semantics are if the method is called multiple times.

For an interface named `Call`, I would normally expect that it will run the operation every time you invoke it and return the result. On the other hand, for a method named `Err`, I would expect it to be just an accessor that returns a previously recorded value.

Two possible options, neither of which I'm fully sold on are,

```go
type Result interface { Err() error } 
// represents the result of calling an operation. Err is an accessor.

type Caller interface{ Call() error }
// represents an action that can fail that has not been run yet.
```

For `Result`, we'd be able to do,

```go
type Result interface { Err() error } 
  func Call(fn func() error) Result
  func Close(io.Closer) Result

// Usage

f, err := ...
defer func() {
  // note that because multierr.Close and Call would perform the operation right away,
  // they suffer from the same problem as multierr.AppendInto(&err, f.Close()).
  multierr.AppendResult(&err, multierr.Close(f))
}()

scanner := bufio.NewScanner(f)
defer multierr.AppendResult(&err, scanner)

multierr.AppendResult(&err, multierr.Call(foo))
```

For `Caller`, we'd be able to do,

```go
type Caller interface{ Call() error }
  type Func func() error
    func (Func) Call() error
  func Close(io.Closer) Caller

// Usage

f, err := ...
defer multierr.AppendCall(&err, multierr.Close(f))

scanner := bufio.NewScanner(f)
defer func() {
    multierr.AppendInto(&err, scanner.Err())
    // (using AppendCall doesn't give us anything here)
}()

multierr.AppendCall(&err, multierr.Func(foo))
```

I'm not sold on either name or structure, but I lean slightly towards the latter (`Caller`) than the former (`Result`) simply because an object to represent the result of an operation doesn't solve the original problem this issue wanted to solve.

**Comment by baez90** [comment]
Personally I'd favor something like:

```go
type Delegate interface {
	Invoke() error
}

type DelegateOf func() error
func Close(closer io.Closer) Delegate
func AppendResult(into *error, call Delegate)


// Usage

defer multierr.AppendResult(&err, multierr.Close(f))

scanner := bufio.NewScanner(f)
defer multierr.AppendResult(&err, multierr.DelegateOf(scanner.Err))
```

I'm also fine with your `Caller` proposal if there is a majority that agrees on that.
The `Result` interface is not an option for me because - like you already mentioned - this would lead the whole issue/PR ad absurdum.

I do understand your concerns regarding the semantics of `Call` and `Err` and I'm not solid either on the current PR which is mostly based on what @prashantv suggested last week. I just tried to make some progress here.
Let's see what the others think and as soon as there is some agreement on anything I'll update the PR accordingly and fix the coverage issue.

**Comment by abhinav** [comment]
Oh, Invoke is a good name! We can call the interface `Invoker`.

```go
type Invoker interface{ Invoke() error }

type Invoke func() error

func Close(io.Closer) Invoker

func AppendInvoke(*error, Invoker) bool
```

I especially like how usage of `type Invoke` will end up looking:

```go
defer multierr.AppendInvoke(&err, multierr.Invoke(scanner.Err))
```

**Comment by baez90** [comment]
Glad to hear you like the name!
I updated the PR accordingly for now.

Let me know if you want me to change anything, any kind of guideline I should take into account or anything else :blush:
