### ISSUE TITLE
Equal Errors showing as different

### ISSUE THREAD

**Issue by gogingersnap777** [uber-go/multierr#83]
I believe showing the equality of errors is broken. Below is my example program showing 

### Run
```bash
$ go run main.go
Nope, they are not the same
TotalError1: 1; 2; 3
TotalError2: 1; 2; 3
```

### `main.go`

```go
package main

import (
	"errors"
	"fmt"

	"go.uber.org/multierr"
)

var (
	Err1 = errors.New("1")
	Err2 = errors.New("2")
	Err3 = errors.New("3")
)

func main() {
	var TotalError1 error
	TotalError1 = multierr.Append(TotalError1, Err1)
	TotalError1 = multierr.Append(TotalError1, Err2)
	TotalError1 = multierr.Append(TotalError1, Err3)

	var TotalError2 error
	TotalError2 = multierr.Append(TotalError2, Err1)
	TotalError2 = multierr.Append(TotalError2, Err2)
	TotalError2 = multierr.Append(TotalError2, Err3)

	if errors.Is(TotalError1, TotalError2) {
		fmt.Println("Yay! They are the same!")
	} else {
		fmt.Println("Nope, they are not the same")
		fmt.Printf("TotalError1: %s\n", TotalError1)
		fmt.Printf("TotalError2: %s\n", TotalError2)
	}
}

```

### `go.mod`

```go
module example

go 1.22.4

require go.uber.org/multierr v1.11.0 // indirect

```

**Comment by tchung1118** [comment]
I think this is an expected behavior of errors.Is. Looking at the implementation of [errors.Is](https://cs.opensource.google/go/go/+/refs/tags/go1.22.4:src/errors/wrap.go;l=53), for errors.Is to return true, either of the following needs to be true:

- some error in err's tree (or err itself) needs to be equal to the target, using `==` operator
- some error in err's tree (or err itself) needs to implement an `Is(error) bool` method and that Is method needs to return true for the given target.

So unless your error type implements an Is method, they need to be exactly the same value, and if your error type is a pointer, they need to be the same pointers.

For example, consider the following:
```go
// example 1
err1 := errors.New("foo")
err2 := errors.New("foo")
fmt.Println(errors.Is(err1, err2)) // prints false

// example 2
wrapped1 := errors.Join(Err1, Err2, Err3)
wrapped2 := errors.Join(Err1, Err2, Err3)
fmt.Println(errors.Is(wrapped1, wrapped2)) // prints false
```
For both examples, errors.Is returns false because the two errors are actually different pointers, which means they are not technically equal, so errors.Is is returning false.
